---
- name: Update and upgrade apt packages
  hosts: iad-2
  become: yes

  tasks:
    - name: Update packages with apt
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade packages with apt
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        upgrade: dist

    - name: Install nfs-common
      ansible.builtin.apt:
        name: rsync
