- hosts: workers
  become: yes
  tasks:
    - name: Install nfs-common
      ansible.builtin.apt:
        name: nfs-common
    - name: Template a file to /etc/file.conf
      ansible.builtin.template:
        src: /templates/multipath.conf
        dest: /etc/multipath.conf
        mode: '0644'
