- hosts: workers
  become: yes
  tasks:
    - name: Install nfs-common
      ansible.builtin.apt:
        name: nfs-common
    - name: Configure multipath
      ansible.builtin.template:
        src: templates/multipath.conf
        dest: /etc/multipath.conf
        mode: '0644'
